name: Rust

on:
  push:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose

      - name: setup git config
        run: |
          git config user.name "Manifest Bot"
          git config user.email "<>"

      - name: commit
        run: |
          git add manifest.json
          git commit -m "feat: added commit"
          git push origin master
